version: '3.8'

services:
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agro_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - agro_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./frontend/web-dashboard
      dockerfile: Dockerfile
    container_name: agro_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/web-dashboard:/app
      - /app/node_modules
    networks:
      - agro_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  agro_network:
    driver: bridge

volumes:
  backend_data:
  frontend_data: